/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_lyoun_serialport_SerialPort */

#ifndef _Included_top_lyoun_serialport_SerialPort
#define _Included_top_lyoun_serialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_lyoun_serialport_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;IIIII)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_top_lyoun_serialport_SerialPort_open
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     top_lyoun_serialport_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_lyoun_serialport_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class top_lyoun_serialport_SerialPort_Builder */

#ifndef _Included_top_lyoun_serialport_SerialPort_Builder
#define _Included_top_lyoun_serialport_SerialPort_Builder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
